# Style & Quality Overrides
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**/*'
    - 'vendor/bundle/**/*'
    - '**/*/.irbrc'

Lint/AssignmentInCondition:
  Enabled: false

Lint/Void:
  Enabled: false

# Disable for now
Lint/UriEscapeUnescape:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 20

Metrics/ParameterLists:
  Max: 10
  CountKeywordArgs: true

Performance/Casecmp:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false
# Disable for now
Performance/HashEachMethods:
  Enabled: false

Style/MixinGrouping:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/NumericLiterals:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/Copyright:
  Enabled: true
  Notice: 'Copyright (\(C\) )?2019 Twitter, Inc.'
  AutocorrectNotice: "# Copyright (C) 2019 Twitter, Inc.\n"
  Exclude:
    - Gemfile

Style/NegatedIf:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SignalException:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
