language: ruby

install: ruby -S bundle install --without development

branches:
  only:
    - master
    - stable

jobs:
  include:
    - stage: test
      script: bundle exec rubocop
      script: bundle exec rake



matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
  include:
    - rvm: 2.3.0
    - rvm: 2.4.0
    - rvm: 2.5.0
    - rvm: 2.6.0
    - rvm: ruby-head
    - rvm: rbx
