language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - rbx-2
  - jruby-head

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

install: ruby -S bundle install --without development
script: bundle exec rake

branches:
  only:
    - master

matrix:
  exclude:
    - rvm: rbx-2
      jdk: openjdk7
    - rvm: rbx-2
      jdk: oraclejdk7
    - rvm: rbx-2
      jdk: oraclejdk8
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: oraclejdk7
    - rvm: 2.0.0
      jdk: oraclejdk8
    - rvm: 2.1
      jdk: openjdk7
    - rvm: 2.1
      jdk: oraclejdk7
    - rvm: 2.1
      jdk: oraclejdk8
    - rvm: 2.2
      jdk: openjdk7
    - rvm: 2.2
      jdk: oraclejdk7
    - rvm: 2.2
      jdk: oraclejdk8
    - rvm: ruby-head
      jdk: openjdk7
    - rvm: ruby-head
      jdk: oraclejdk7
    - rvm: ruby-head
      jdk: oraclejdk8
